<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TargetPlatformMoniker>Windows,Version=7.0</TargetPlatformMoniker>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ComboLab</RootNamespace>
    <AssemblyName>ComboLab</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove=".verify\**\*.cs" />
  </ItemGroup>

</Project>
